name: Comment on opened PR about Preview Website URL

on:
  pull_request:
    types: [opened]
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  DOCUSAURUS_URL: https://pr-${{ github.event.number }}-pm4h-docs-sabienupv.surge.sh

jobs:
  comment:
    name: Comment on PR with Preview Website URL
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview Website deployment URL: ${{ env.DOCUSAURUS_URL }}\n\nTo know if the preview website has been deployed, check if this PR shows a message about an active deployment.\nFor convenience, a "preview" label will be added to this PR when the deployment is available, and it will be removed when torn down.\nIf this PR is closed or merged, the deployment will be automatically torn down. If you re-open the PR, a new deployment will be performed.'
            })