name: Comment on opened PR about Preview Website URL

on:
  pull_request:
    types: [opened]
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  DOCUSAURUS_URL: https://pr-${{ github.event.number }}-pm4h-docs-sabienupv.surge.sh

jobs:
  comment:
    name: Comment on PR with Preview Website URL
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🚀 Preview Deployment
              A preview of this Pull Request is available at the following URL:

              🔗 **${{ env.DOCUSAURUS_URL }}**

              This preview will be automatically updated with new commits and will be active until the PR is merged or closed.

              The \`preview\` label is automatically added or removed to indicate if the preview is live.

              **_Note:_** You can also view the deployment status in this PR. If you see an 'active deployment' message at the bottom, it means the preview is live. You can click on it for more details. If the deployment failed, a failure message should appear in the 'Checks' section.`
              `
            })