name: Build and Deploy Preview Website to Surge

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

# Prevent multiple deployments from running concurrently
# (https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCUSAURUS_URL: https://pr-${{ github.event.number }}-pm4h-docs-sabienupv.surge.sh
  DOCUSAURUS_BASE_URL: /

jobs:
  # This is done because cancelled runs are shown as failed in the GitHub UI,
  # which can be misleading, because cancel-in-progress will cancel the previous run
  # if a new one is triggered, and that should not be shown as a failure
  # (and when the PR is re-opened and there are new commits, the workflow is triggered twice,
  # so for that case we need to cancel the extra run, and it should not be shown as a failure)
  # (Reference: https://github.com/orgs/community/discussions/8336)
  delete-cancelled-runs-for-this-workflow:
    name: Delete cancelled runs for this workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { data: currentRun } = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });

            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: currentRun.workflow_id,
              status: 'cancelled'
            });
            
            for (const run of runs.workflow_runs) {
              if (run.id !== context.runId) {
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                });
              }
            }
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build

  deploy:
    name: Deploy Preview to Surge
    needs: build

    # Deploy to the staging environment
    environment:
      name: staging
      url: ${{ env.DOCUSAURUS_URL }}

    runs-on: ubuntu-latest
    steps:
      # We need to checkout the code again to get the package-lock.json file,
      # which is used to be able to reuse cached dependencies by npm in previous runs
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build

      - name: Deploy Preview
        run: npx --yes surge ./build --domain ${{ env.DOCUSAURUS_URL }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Add preview label to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['preview']
            })

      - name: Add comment to PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const success = '${{ job.status }}' === 'success';
            const actionUrl = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const body = success ? '✅🚀 Preview Website deployed at: ${{ env.DOCUSAURUS_URL }}' : `❌🚀 Preview Website failed to deploy. Check the GitHub action for details: ${actionUrl}`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })