name: Build and Deploy Preview Website to Surge

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  DOCUSAURUS_URL: https://pr-${{ github.event.number }}-pm4h-docs-sabienupv.surge.sh
  DOCUSAURUS_BASE_URL: /

jobs:
  test-build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build

  test-deploy:
    name: Deploy Preview to Surge
    needs: test-build

    # Prevent multiple deployments from running concurrently
    concurrency:
      group: staging-ci-${{ github.ref }}
      cancel-in-progress: true

    # Deploy to the staging environment
    # (this eliminates the need to add custom comments to the PR to show the deployment URL,
    # because the URL that we pass here will be shown by GitHub in the PR as a deployment URL)
    environment:
      name: staging
      url: ${{ env.DOCUSAURUS_URL }}

    runs-on: ubuntu-latest
    steps:
      # We need to checkout the code again to get the package-lock.json file,
      # which is used to be able to reuse cached dependencies by npm in previous runs
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build

      - name: Deploy Preview
        run: npx --yes surge ./build --domain ${{ env.DOCUSAURUS_URL }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
